# Generated by Django 3.2.3 on 2021-06-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
