# Generated by Django 3.2.3 on 2021-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0002_profile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
