# Generated by Django 3.2.3 on 2021-06-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0003_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
