# Generated by Django 3.2.3 on 2021-06-01 22:04

from django.db import migrations, models
import sam.models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0004_auto_20210601_2156'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', sam.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
